site_name: MSA (Multi-perturbation Shapley value Analysis)
theme:
  name: material

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition # alerts
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

use_directory_urls: false

plugins:
- search
- mkdocs-jupyter
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true